Update ont-zte-f601.md
hack-gpon/hack-gpon.github.io pull request #181
Opened 2023-04-25 09:51 UTC by stich86

- add external script to enable telnet
- add other informations

2023-05-02 12:23 UTC, simonebortolin approved these changes

2023-05-02 19:56 UTC, nanomad requested changes

2023-05-02 19:56 UTC, nanomad commented on _ont/ont-zte-f601.md
> +You can also clone currently running image into other slot using this command:
```suggestion
You can also clone the currently running image into other slot using this command:
```

2023-05-02 19:56 UTC, nanomad commented on _ont/ont-zte-f601.md
> +{% include alert.html content="Commands have been tested on V6/V7 HW rev on TIM and OF firmware" alert="Note"  icon="svg-info" color="blue" %}
```suggestion
{% include alert.html content="Commands have been tested on V6/V7 HW rev. on TIM and OpenFiber firmwares" alert="Note"  icon="svg-info" color="blue" %}
```

2023-05-02 19:56 UTC, nanomad commented on _ont/ont-zte-f601.md
> +{% include alert.html content="This is an external script ([ZTE Telnet enabled](https://github.com/douniwan5788/zte_modem_tools)), so use at your own risk! Credential doesn't survive at reboot!" aler
```suggestion
{% include alert.html content="This is an external script ([ZTE Telnet enabled](https://github.com/douniwan5788/zte_modem_tools)), so use it at your own risk! Credential doesn't survive at reboot!" alert="Note"  icon="svg-info" color="blue" %}
```

2023-05-02 19:56 UTC, nanomad commented on _ont/ont-zte-f601.md
> +{% include alert.html content="For Italian users, it only works on versions V6.0.10N40 (TIM) and V6.0.10P6N7 (OpenFiber)" alert="Note"  icon="svg-info" color="blue" %}
```suggestion
{% include alert.html content="For italian users, it only works on versions V6.0.10N40 (TIM) and V6.0.10P6N7 (OpenFiber)" alert="Note"  icon="svg-info" color="blue" %}
```

2023-05-02 19:56 UTC, nanomad commented on _ont/ont-zte-f601.md
> +To see omcidebug messages on Telnet you need to perform this command (just first time of each connection):
```suggestion
To see omcidebug messages on Telnet you need to execute this command (just the first time of each connection):
```

2023-05-02 19:56 UTC, nanomad commented on _ont/ont-zte-f601.md
> +This command will print out the result like this one:
```suggestion
This command will print out a result like this one:
```

2023-05-02 19:56 UTC, nanomad commented on _ont/ont-zte-f601.md
> +{% include alert.html content="You have to change S/N and the VID. 2176 is for the VID (first 4 letters of the S/N) and 2177 is for the last 8 digits" alert="Note"  icon="svg-info" color="blue" %}
```suggestion
{% include alert.html content="You have to change S/N and the VID. 2176 is for the VID (first 4 letters of the S/N) and 2177 is for the last 8 digits of the S/N" alert="Note"  icon="svg-info" color="blue" %}
```

2023-05-02 19:56 UTC, nanomad commented on _ont/ont-zte-f601.md
> +Run the script with the following parameters, you can use `-h` for help. In this example we are just replace firmware version with `V6.0.10N40`. You can put your own version here, maximium 15 charact
```suggestion
Run the script with the following parameters, you can use `-h` for help. In this example we are just replacing the firmware version with `V6.0.10N40`. You can put your own version here, maximium 15 characters. This parameter is mandatory:
```

2023-05-02 19:56 UTC, nanomad commented on _ont/ont-zte-f601.md
> +If you have create partition dump with different name, please put the correct name instead of `kernel0`
```suggestion
If you need to create a partition dump with a different name, please put the correct name instead of `kernel0`
```

2023-05-02 19:56 UTC, nanomad commented on _ont/ont-zte-f601.md
> +If you are swapping from TIM to OpenFiber Firmware, or viceversa, before reboot the ONT you have to run these two command based on the firmware version:
```suggestion
If you are swapping from TIM to OpenFiber Firmware, or viceversa, you have to run these two command before rebooting the ONT based on the firmware version:
```

2023-05-02 19:56 UTC, nanomad commented on _ont/ont-zte-f601.md
> +ZTE has create various region code that loads default valuse based on local ISP, this configuration can be changed using this command:
```suggestion
ZTE has created various region codes that load default valuse based on the local ISP. This configuration can be changed using this command:
```

2023-05-27 12:37 UTC, nanomad approved these changes

2023-05-27 12:37 UTC, merged