WIP: Update LEOX lxt-010s-h wiki
hack-gpon/hack-gpon.github.io pull request #44
Opened 2022-11-29 10:39 UTC by stich86

2022-11-29 11:51 UTC, simonebortolin commented on _ont/ont-leox-lxt-010s-h.md
> +# List of partitions
List of partition are (in all other pages) a second level header, use `##` inside `#`.

2022-11-29 11:52 UTC, simonebortolin commented on _ont/ont-leox-lxt-010s-h.md
> +## Known Bugs
Known Bugs are (in all other pages) a first level header, use `#` inside `##.`

2022-11-29 11:53 UTC, simonebortolin commented on _ont/ont-leox-lxt-010s-h.md
> +- V3.3.4L4rc1 (contains fix for 2.5GbE mode)
add this info:
`There is a new firmware avaliable from LeoLabs that fix this issue`
and move this info:
`contains fix for 2.5GbE mode
`with a  alert box like this:
`{% include alert.html content="Try PIN 10 or other GND PINs if it doesn't work with 14." alert="Note" icon="svg-warning" color="yellow" %}`

2022-11-29 11:54 UTC, simonebortolin commented on _ont/ont-leox-lxt-010s-h.md
> +| LAN_SDS_MODE = 1     | 1GbE with auto-neg on                |
if you know specify whether the other modes 2 to 6 exist or not

2022-11-29 12:03 UTC, simonebortolin requested changes

2022-11-29 12:03 UTC, simonebortolin commented on _ont/ont-leox-lxt-010s-h.md
> +The stick has a TTL 3.3v UART console (115200bps - 8Bit) that can be accessed from the top surface. To accept TX line commands, GND of TTL adapter should be attached to the stick's shield:
I do not remember whether this is the syntax already used on other pages or whether it is different. I don't think there is a capital B of bit on other pages.

2022-11-29 12:05 UTC, simonebortolin commented
finally, will you create me a nice commit message that will take the place of all those you have already written?

2022-11-29 12:17 UTC, merged

2023-08-19 18:39 UTC, qatar2030 commented
i have LEOX GPON STICK LXT-010S-H and it was working great with mikrotik rb5009 and when i change mode from flash set LAN_SDS_MODE 1 to flash set LAN_SDS_MODE 8 the sfp stop working any help please

2023-08-19 19:08 UTC, simonebortolin commented
> i have LEOX GPON STICK LXT-010S-H and it was working great with mikrotik rb5009 and when i change mode from flash set LAN_SDS_MODE 1 to flash set LAN_SDS_MODE 8 the sfp stop working any help please

Please open a discussion/issue

2023-08-19 19:12 UTC, stich86 commented
Which version of RouterOS and Firmware do you have?

The support was added by 7.3 or later.
Make sure that firmware (under System/RouterBOARD) is update otherwise 2.5Gbit// doesn't work

2023-08-20 06:52 UTC, qatar2030 commented
> Which version of RouterOS and Firmware do you have?
> 
> The support was added by 7.3 or later. Make sure that firmware (under System/RouterBOARD) is update otherwise 2.5Gbit// doesn't work

My SFP firmware version is V3.3.4L4rc1 (Fix 2.5GbE HiSGMII) and my Mikrotik version 7.11
![Screenshot 2023-08-20 094654](https://github.com/hack-gpon/hack-gpon.github.io/assets/89544455/9fecaac2-76f9-4c41-b798-32007ec55f9c)
![Screenshot 2023-08-20 094711](https://github.com/hack-gpon/hack-gpon.github.io/assets/89544455/88c32349-cef6-465c-a6e6-0efc1d1158f1)
and someone taled me that I have to have media convertor 2.5G instead 1G to change sfp mode to fiber
![Screenshot 2023-08-20 095302](https://github.com/hack-gpon/hack-gpon.github.io/assets/89544455/e918cb17-04cd-4bc8-bb4b-1d6a5eec2dc4)

2023-08-20 07:59 UTC, simonebortolin commented
Please open a NEW issue