add CIG G-97CP and Hisense LTE3415
hack-gpon/hack-gpon.github.io pull request #63
Opened 2022-12-20 10:33 UTC by simonebortolin

2022-12-20 10:34 UTC, simonebortolin commented
- [ ] fix ontuser/ont for login
- [ ] fix sdk on zte and nokia

2022-12-23 13:00 UTC, nanomad requested changes

2022-12-23 13:00 UTC, nanomad commented on _ont/ont-nokia-g-010g-t.md
> +| Telnet      | ✅ user `ONTUSER` password should be calculated, calculated by hash of a username and serial number |
```suggestion
| Telnet      | ✅ user `ONTUSER`, password should be computed based on a hash of the username and the serial number |
```

2022-12-23 13:00 UTC, nanomad commented on _ont/ont-zte-f6005.md
> +| Telnet      | ✅ user `ont` password should be calculated, calculated by hash of a username and serial number |
```suggestion
| Telnet      | ✅ user `ont`, password should be computed based on a hash of the username and the serial number |
```

2022-12-25 17:20 UTC, ErnyTech approved these changes

2022-12-26 09:13 UTC, nanomad requested changes

2022-12-26 09:13 UTC, nanomad commented on _ont/ont-nokia-g-010g-p.md
> +| IP address  | 192.168.100.1  (factory reseted unit use IP 10.89.42.157/16) |
```suggestion
| IP address  | 192.168.100.1  (after a factory reset the ONT uses 10.89.42.157/16) |
```

2022-12-26 09:13 UTC, nanomad commented on _ont/ont-nokia-g-010g-q.md
> +| Telnet                | ✅ user `ONTUSER`, but open GponCLI and not GponSLID                                                              |
```suggestion
| Telnet                | ✅ user `ONTUSER`, but has access to GponCLI and not GponSLID                                                              |
```

2022-12-26 09:13 UTC, nanomad commented on _ont/ont-nokia-g-010g-r.md
> +| Telnet      | ✅ user `admin`, password `1234`, but open GponCLI and not GponSLID |
```suggestion
| Telnet      | ✅ user `admin`, password `1234`, but has access to GponCLI and not GponSLID |
```

2022-12-26 09:13 UTC, nanomad commented on _ont/ont-nokia-use.md
> +Once you're logged in, a custom menu will be shown, and you'll be able to access the linux shell by first typing `system` and finally `shell`:
```suggestion
Once you're logged in, a custom menu will be shown and you'll be able to access the linux shell by first typing `system` followed by `shell`:
```

2022-12-26 09:13 UTC, nanomad commented on _ont/ont-nokia-use.md
> +The enable password can be calculated using the following form:
```suggestion
The enable password can be generated using the following form:
```

2022-12-26 09:13 UTC, nanomad commented on _ont/ont-zte-f6005.md
> +To calculate the password for telnet access, you can use this tool, simply by entering the S/N
```suggestion
You can use this tool to generate the password for telnet access
```

2022-12-26 09:13 UTC, nanomad commented on _includes/cig_password.html
> +            <input type="submit" class="btn btn-primary" value="Calculate!" id="submit">
```suggestion
            <input type="submit" class="btn btn-primary" value="Generate!" id="submit">
```

2022-12-26 09:32 UTC, nanomad approved these changes

2022-12-26 09:32 UTC, merged